---
driver:
  name: vagrant

platforms:
  - name: debian-jessie-64
    driver_config:
      box: ssplatt/salt-deb-8
  - name: centos7-64
    driver_config:
      box: rchrd/centos-7-x64-salt
  # - name: arch-64
  #   driver_config:
  #     box: terrywang/archlinux

provisioner:
  name: salt_solo
  salt_version: 2016.3.2
  data_path: test/shared
  is_file_root: true
  pillars:
    top.sls:
      base:
        '*':
          - tomcat
    tomcat.sls:
      tomcat:
        security: 'no'
        expires_when: '2 weeks'
        manager:
          roles:
            - manager-gui
            - manager-script
            - manager-jmx
            - manager-status
          users:
            saltuser1:
              passwd: RfgpE2iQwD
              roles: manager-gui,manager-script,manager-jmx,manager-status
            saltuser2:
              passwd: RfgpE2iQwD
              roles: manager-gui,manager-script,manager-jmx,manager-status
        limit_soft: 48000
        java_opts:
          - 'Djava.awt.headless=true'
          - 'Xmx128m'
          - 'XX:MaxPermSize=256m'
          - 'XX:+UseConcMarkSweepGC'
          - 'XX:+CMSIncrementalMode'
          - 'Dlog4j.configuration=file:/path/to/log4j.properties'
          - 'Dlogback.configurationFile=/path/to/logback.xml'
        logfile_days: 14
        logfile_compress: 1
        jvm_tmp: /tmp/tomcat
        authbind: no
        cluster: 
          simple: true
        sites:
            example.com: 
              name: example.com
              appBase: ../webapps/myapp
              path: ''
              docBase: '/var/lib/tomcat7/webapps/myapp'
              unpackWARs: "true"
              autoDeploy: "true"
              reloadable: "true"
              debug: 0
            example.net:
              appBase: ../webapps/myapp2
              path: ''
              docBase: '/var/lib/tomcat7/webapps/myapp2'
              unpackWARs: "true"
              autoDeploy: "true"
              reloadable: "true"
              debug: 0        
        context:
          Environment:
            env.first:
              name: env.first
              value: first.text
              type: java.lang.String
              override: true
          Listener:
            second:
              className: org.apache.catalina.core.AprLifecycleListener
              SSLEngine: "on"

suites:
  - name: tomcat_install
    provisioner:
      state_top:
        base:
          '*':
            - tomcat
            - tomcat.manager
  - name: tomcat_config
    provisioner:
      state_top:
        base:
          '*':
            - tomcat.config
  - name: tomcat_native
    provisioner:
      state_top:
        base:
          '*':
            - tomcat.native
  - name: tomcat_manager
    provisioner:
      state_top:
        base:
          '*':
            - tomcat.manager
  - name: tomcat_expires
    provisioner:
      state_top:
        base:
          '*':
            - tomcat.expires
  - name: tomcat_context
    provisioner:
      state_top:
        base:
          '*':
            - tomcat.context
  - name: tomcat_cluster
    provisioner:
      state_top:
        base:
          '*':
            - tomcat.cluster                
  - name: tomcat_vhosts
    provisioner:
      state_top:
        base:
          '*':
            - tomcat.vhosts
  - name: tomcat
    provisioner:
      state_top:
        base:
          '*':
            - tomcat
            - tomcat.manager           
            - tomcat.config          
            - tomcat.native           
            - tomcat.context          
            - tomcat.expires          
            - tomcat.vhosts          
            - tomcat.cluster          
