<%
require 'yaml'

formula = YAML.load_file('FORMULA')
formula_name = formula['name']
%>
---
verifier:
  name: inspec

platforms:
  - name: ubuntu-14.04
  - name: ubuntu-16.04
  - name: debian-7
  - name: debian-8
  - name: centos-6
  - name: centos-7

provisioner:
  name: salt_solo
  salt_install: bootstrap
  salt_bootstrap_url: https://bootstrap.saltstack.com
  salt_version: latest
  log_level: <%= ENV['SALT_DEBUG_LEVEL'] || 'info' %>
  formula: <%= formula_name %>
  data_path: test/shared
  is_file_root: true
  pillars:
    top.sls:
      base:
        '*':
          - tomcat

    tomcat.sls:
      tomcat:
        security: no
        java_home: /usr/lib/jvm/default-java
        java_opts:
          - 'Djava.awt.headless=true'
          - 'Xmx128m'
          - 'XX:MaxPermSize=256m'
          - 'XX:+UseConcMarkSweepGC'
          - 'XX:+CMSIncrementalMode'
          - 'Dlog4j.configuration=file:/path/to/log4j.properties'
          - 'Dlogback.configurationFile=/path/to/logback.xml'
        jsp_compiler: javac
        logfile_days: 14
        logfile_compress: 1
        jvm_tmp: /tmp/tomcat
        authbind: no
        expires_when: '2 weeks'
        with_haveged: true
        haveged_enabled: true
        catalina_base: /usr/share/tomcat
        catalina_home: /usr/share/tomcat
        catalina_tmpdir: /var/cache/tomcat/temp
        catalina_pid: /var/run/tomcat.pid

        limit:
          soft: 48000
          hard: 64000
        connector:
          example_connector:
            port: 8443
            protocol: 'org.apache.coyote.http11.Http11Protocol'
            connectionTimeout: 20000
            URIEncoding: 'UTF-8'
            redirectPort: 8443
            maxHttpHeaderSize: 8192
            maxThreads: 150
            minSpareThreads: 25
            enableLookups: 'false'
            disableUploadTimeout: 'true'
            acceptCount: 100
            scheme: https
            secure: 'true'
            SSLEnabled: 'true'
            clientAuth: 'false'
            sslProtocol: TLS
            keystoreFile: '/path/to/keystoreFile'
            keystorePass: 'somerandomtext'
        sites:
            example.com:
              name: some_string
              appBase: ../webapps/myapp
              path: ''
              docBase: '../webapps/ROOT'
              alias: some_string
              unpackWARs: "true"
              autoDeploy: "true"
              reloadable: "true"
              debug: 0
        manager:
          roles:
            - manager-gui
            - manager-script
            - manager-jmx
            - manager-status
          users:
            saltuser1:
              passwd: RfgpE2iQwD
              roles: manager-gui,manager-script,manager-jmx,manager-status
            saltuser2:
              passwd: RfgpE2iQwD
              roles: manager-gui,manager-script,manager-jmx,manager-status
        cluster:
          simple: true
        context:
          Environment:
            env.first:
              name: env.first
              value: first.text
              type: java.lang.String
              override: true
          Listener:
            second:
              className: org.apache.catalina.core.AprLifecycleListener
              SSLEngine: "on"
          Resource:
            jdbc:
              name: jdbc/__postgres
              auth: Container
              type: javax.sql.DataSource
              driverClassName: org.postgresql.Driver
              url: jdbc:postgresql://db.server/dbname
              user: dbuser
              password: aycaramba!
              maxActive: 20
              maxIdle: 10
              maxWait: -1
          ResourceLink:
            any_name_here_will_be_ignored:
              name: linkToGlobalResource
              global: simpleValue
              type: java.lang.Integer
suites:
  - name: tomcat_install
    provisioner:
      state_top:
        base:
          '*':
            - tomcat
            - tomcat.manager

  - name: tomcat_config
    provisioner:
      state_top:
        base:
          '*':
            - tomcat.config
            - tomcat.manager
            - tomcat.vhosts
            - tomcat.expires
            - tomcat.context
            - tomcat.cluster
  - name: tomcat_native
    provisioner:
      state_top:
        base:
          '*':
            - tomcat.native
  - name: tomcat_manager
    provisioner:
      state_top:
        base:
          '*':
            - tomcat.manager
  - name: tomcat_expires
    provisioner:
      state_top:
        base:
          '*':
            - tomcat.expires
  - name: tomcat_context
    provisioner:
      state_top:
        base:
          '*':
            - tomcat.context
  - name: tomcat_cluster
    provisioner:
      state_top:
        base:
          '*':
            - tomcat.cluster